// import { ReactNode } from 'react';
// import { Box } from '@mui/material';
// import { Providers } from './providers';
// import { Toaster } from 'react-hot-toast';

// // export const metadata = {
// //   title: 'Tarot Couch Helper',
// //   description: 'Generated by Next.js with Material UI',
// // };

// export default function RootLayout({ children }: { children: ReactNode }) {
//   return (
//     <html>
//       <head>
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         {/* PWA Manifest */}
//         <link rel="manifest" href="/manifest.json" />
//         {/* iOS icons */}
//         <link
//           rel="apple-touch-icon"
//           sizes="180x180"
//           href="/icons/ios/180.png"
//         />
//         <link
//           rel="apple-touch-icon"
//           sizes="152x152"
//           href="/icons/ios/152.png"
//         />
//         <link
//           rel="apple-touch-icon"
//           sizes="120x120"
//           href="/icons/ios/120.png"
//         />
//         <link rel="apple-touch-icon" sizes="76x76" href="/icons/ios/76.png" />

//         {/* Windows */}
//         <meta name="msapplication-TileColor" content="#1E1E3F" />
//         <meta
//           name="msapplication-TileImage"
//           content="/icons/windows11/Square150x150Logo.scale-150.png"
//         />

//         {/* Theme */}
//         <meta name="theme-color" content="#DAB0FF" />
//         <link
//           rel="preload"
//           href="/fonts/PlayfairDisplay-Regular.woff2"
//           as="font"
//           type="font/woff2"
//           crossOrigin="anonymous"
//         />
//         <link
//           rel="preload"
//           href="/fonts/PlayfairDisplay-Bold.woff2"
//           as="font"
//           type="font/woff2"
//           crossOrigin="anonymous"
//         />
//         <link
//           rel="preload"
//           href="/fonts/PlayfairDisplay-Italic.woff2"
//           as="font"
//           type="font/woff2"
//           crossOrigin="anonymous"
//         />

//         <style
//           dangerouslySetInnerHTML={{
//             __html: `
//               @font-face {
//                 font-family: 'Playfair Display';
//                 src: url('/fonts/PlayfairDisplay-Regular.woff2') format('woff2');
//                 font-weight: 400;
//                 font-style: normal;
//                 font-display: swap;
//               }

//               @font-face {
//                 font-family: 'Playfair Display';
//                 src: url('/fonts/PlayfairDisplay-Bold.woff2') format('woff2');
//                 font-weight: 700;
//                 font-style: normal;
//                 font-display: swap;
//               }

//               @font-face {
//                 font-family: 'Playfair Display';
//                 src: url('/fonts/PlayfairDisplay-Italic.woff2') format('woff2');
//                 font-weight: 400;
//                 font-style: italic;
//                 font-display: swap;
//               }

//               body {
//                 font-family: 'Playfair Display', serif;
//               }
//             `,
//           }}
//         />
//         <link
//           rel="preload"
//           href="/background.webp"
//           as="image"
//           type="image/webp" // Укажите правильный тип, если уверены (например, image/png, image/jpeg)
//           fetchPriority="high" // Повышаем приоритет загрузки
//         />
//         {/* Google Analytics */}
//         <script
//           async
//           src="https://www.googletagmanager.com/gtag/js?id=G-GPB084M7TR"
//         ></script>
//         <script
//           dangerouslySetInnerHTML={{
//             __html: `
//               window.dataLayer = window.dataLayer || [];
//               function gtag(){dataLayer.push(arguments);}
//               gtag('js', new Date());
//               gtag('config', 'G-GPB084M7TR');
//             `,
//           }}
//         />
//       </head>
//       <body
//         style={{
//           display: 'flex',
//           flexDirection: 'column',
//           minHeight: '100vh',
//           margin: 0,
//           padding: 0,
//           width: '100%',
//           maxWidth: '100vw',
//           overflowX: 'hidden',
//           boxSizing: 'border-box',
//         }}
//       >
//         <Providers>
//           <Toaster position="top-right" />
//           <Box sx={{ flex: 1 }}>{children}</Box>
//         </Providers>
//       </body>
//     </html>
//   );
// }


import { ReactNode } from 'react';
import { Box } from '@mui/material';
import { Providers } from './providers';
import { Toaster } from 'react-hot-toast';

// РАСКОММЕНТИРУЕМ и меняем только title и description:
export const metadata = {
  title: 'TranslateMe | Real-Time Audio Translation',
  description: 'AI-powered real-time translation for videos, meetings, and streams.',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        style={{
          display: 'flex',
          flexDirection: 'column',
          minHeight: '100vh',
          margin: 0,
          padding: 0,
          width: '100%',
          maxWidth: '100vw',
          overflowX: 'hidden',
          boxSizing: 'border-box',
        }}
      >
        <Providers>
          <Toaster position="top-right" />
          <Box sx={{ flex: 1 }}>{children}</Box>
        </Providers>
      </body>
    </html>
  );
}